In [1]:
import pandas as pd
import numpy as np

In [3]:
my_data=[10,20,30]
arr=np.array(my_data)
labels=['a','b','c']
print(type(my_data),type(arr),type(labels))

<class 'list'> <class 'numpy.ndarray'> <class 'list'>

In [5]:
s1=pd.Series(my_data) #series can be created via list
s1

0    10
1    20
2    30
dtype: int64

In [7]:
s2=pd.Series(my_data,index=labels)
s2

a    10
b    20
c    30
dtype: int64

In [9]:
#from dictionary

dict={'a':1,'b':2,'c':3}

s3=pd.Series(dict)
s3

a    1
b    2
c    3
dtype: int64

In [11]:
s3.index

Index(['a', 'b', 'c'], dtype='object')

In [13]:
#s3[0]
s3['a']

1

In [15]:

dict={'a':[1,2],'b':[2,2],'c':3}

s31=pd.Series(dict)
s31

a    [1, 2]
b    [2, 2]
c         3
dtype: object

In [17]:
# from scalar

num=10

s4=pd.Series(num,index=range(5))
s4

0    10
1    10
2    10
3    10
4    10
dtype: int64

## accessing series

In [24]:
ser= pd.Series(data=range(1,11))

In [26]:
ser

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [28]:
#first element of series
ser[0]

1

In [30]:
#last element
ser[9]  # ser[-1]

10

In [32]:
ser[:3]#first 3 element

0    1
1    2
2    3
dtype: int64

In [34]:
ser1=pd.Series([1,2,3],index=[0,2,4])
ser1

0    1
2    2
4    3
dtype: int64

In [36]:
ser1.index

Index([0, 2, 4], dtype='int64')

In [38]:
ser.index #series index

RangeIndex(start=0, stop=10, step=1)

In [40]:
ser.values #values in series

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [42]:
# accessing by label
ser= pd.Series(data=[0,1,2,3,4], index=['a','b','c','d','e'])
ser

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [44]:
ser['b']

1

In [46]:
#multiple values
ser[['a','e','c']]

a    0
e    4
c    2
dtype: int64

In [48]:
ser['f']

KeyError: 'f'

## Dataframe

In [50]:
data=['Rob','jerry','John','Bobby','Manny']
data

['Rob', 'jerry', 'John', 'Bobby', 'Manny']

In [52]:
type(data)

list

In [56]:
df1=pd.DataFrame(data,columns=['Fullname'])
df1

  Fullname
0      Rob
1    jerry
2     John
3    Bobby
4    Manny

In [58]:
type(ser11)

NameError: name 'ser11' is not defined

In [60]:
ser11=pd.Series(data)
ser11

0      Rob
1    jerry
2     John
3    Bobby
4    Manny
dtype: object

In [62]:
data1=[['Rob',25],['Bob',34]]
data1

[['Rob', 25], ['Bob', 34]]

In [64]:
df2=pd.DataFrame(data1)
df2

     0   1
0  Rob  25
1  Bob  34

In [66]:
ser22=pd.Series(data1)

In [68]:
#via dictionary

dict1={'name':['rob','bob','sam','jenny'],'Age':[25,30,34,45]}
dict1

{'name': ['rob', 'bob', 'sam', 'jenny'], 'Age': [25, 30, 34, 45]}

In [70]:
df1=pd.DataFrame(dict1,index=['r','b','s','j'])

In [72]:
df1

    name  Age
r    rob   25
b    bob   30
s    sam   34
j  jenny   45

In [74]:
df1.loc['r']

name    rob
Age      25
Name: r, dtype: object

In [76]:
df1.iloc[0]

name    rob
Age      25
Name: r, dtype: object

In [80]:
# list of dictionary

data1=[{'name':'bob','age':25},{'name':'jenny','age':30},{'name':'samira'}]
print(data1)
df1=pd.DataFrame(data1)
print(df1)

[{'name': 'bob', 'age': 25}, {'name': 'jenny', 'age': 30}, {'name': 'samira'}]
     name   age
0     bob  25.0
1   jenny  30.0
2  samira   NaN

In [82]:
# from series

df1=pd.DataFrame({'name':pd.Series(['rob','jen','bob'])})
print(df1)

df2=pd.DataFrame(pd.Series(['rob','jen','bob']))
df2

  name
0  rob
1  jen
2  bob

     0
0  rob
1  jen
2  bob

## Data via file

In [93]:
import pandas as pd

df=pd.read_csv('loan.csv',sep=',')
#df=pd.read_xlxs("loan.xlsx")
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [95]:
# first few rows
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [97]:
type(df)

pandas.core.frame.DataFrame

In [99]:
#last few rows
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [101]:
#general information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [103]:
#dataype
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [105]:
# column names
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [107]:
#dimension of dataframe
df.shape

(614, 13)

In [111]:
#check missing values per column
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [113]:
df.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [115]:
#unique 
df.nunique()

Loan_ID              614
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
Loan_Status            2
dtype: int64

In [121]:
#drop missing
df.dropna(inplace=True)  # inplace=True
df.head(30)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
31,LP001095,Male,No,0,Graduate,No,3167,0.0,74.0,360.0,1.0,Urban,N
32,LP001097,Male,No,1,Graduate,Yes,4692,0.0,106.0,360.0,1.0,Rural,N
33,LP001098,Male,Yes,0,Graduate,No,3500,1667.0,114.0,360.0,1.0,Semiurban,Y
34,LP001100,Male,No,3+,Graduate,No,12500,3000.0,320.0,360.0,1.0,Rural,N
37,LP001112,Female,Yes,0,Graduate,No,3667,1459.0,144.0,360.0,1.0,Semiurban,Y
38,LP001114,Male,No,0,Graduate,No,4166,7210.0,184.0,360.0,1.0,Urban,Y
39,LP001116,Male,No,0,Not Graduate,No,3748,1668.0,110.0,360.0,1.0,Semiurban,Y

In [123]:
df.shape

(480, 13)

In [125]:
df1=pd.read_csv('loan.csv',sep=',')
df1.shape

(614, 13)

In [50]:
df1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [127]:
df1.dropna(axis=1)

,Loan_ID,Education,ApplicantIncome,CoapplicantIncome,Property_Area,Loan_Status
0,LP001002,Graduate,5849,0.0,Urban,Y
1,LP001003,Graduate,4583,1508.0,Rural,N
2,LP001005,Graduate,3000,0.0,Urban,Y
3,LP001006,Not Graduate,2583,2358.0,Urban,Y
4,LP001008,Graduate,6000,0.0,Urban,Y
...,...,...,...,...,...,...
609,LP002978,Graduate,2900,0.0,Rural,Y
610,LP002979,Graduate,4106,0.0,Rural,Y
611,LP002983,Graduate,8072,240.0,Urban,Y
612,LP002984,Graduate,7583,0.0,Urban,Y
613,LP002990,Graduate,4583,0.0,Semiurban,N

In [129]:
df1.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [131]:
df1.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

## Selection, Creation, and Deletion

In [39]:
# column operation
#selection
#df[col_name] , df[[col1,col2,col3,..]]
df1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [133]:
type(df1[['Loan_ID']])

pandas.core.frame.DataFrame

In [137]:
df1[0:3]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [139]:
df1[:,0:3]

InvalidIndexError: (slice(None, None, None), slice(0, 3, None))

In [141]:
df1[['Loan_ID','Gender','Married']]

      Loan_ID  Gender Married
0    LP001002    Male      No
1    LP001003    Male     Yes
2    LP001005    Male     Yes
3    LP001006    Male     Yes
4    LP001008    Male      No
..        ...     ...     ...
609  LP002978  Female      No
610  LP002979    Male     Yes
611  LP002983    Male     Yes
612  LP002984    Male     Yes
613  LP002990  Female      No

[614 rows x 3 columns]

In [143]:
#Creation
#df[new_col]=name of col
df1['Income']=df1['ApplicantIncome']+df1['CoapplicantIncome']
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Income
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,5849.0
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,6091.0
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,3000.0
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,4941.0
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,6000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,2900.0
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,4106.0
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,8312.0
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,7583.0
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,4583.0

In [145]:
#deletion
#df.drop(cols)
df1.drop(['Income'],inplace=True,axis=1)#axis=1?

In [147]:
df1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [149]:
#row operation
#selection
#iloc[index]
#loc[row number] 

df1.loc[0]

Loan_ID              LP001002
Gender                   Male
Married                    No
Dependents                  0
Education            Graduate
Self_Employed              No
ApplicantIncome          5849
CoapplicantIncome         0.0
LoanAmount                NaN
Loan_Amount_Term        360.0
Credit_History            1.0
Property_Area           Urban
Loan_Status                 Y
Name: 0, dtype: object

In [151]:
df1.iloc[0]

Loan_ID              LP001002
Gender                   Male
Married                    No
Dependents                  0
Education            Graduate
Self_Employed              No
ApplicantIncome          5849
CoapplicantIncome         0.0
LoanAmount                NaN
Loan_Amount_Term        360.0
Credit_History            1.0
Property_Area           Urban
Loan_Status                 Y
Name: 0, dtype: object

In [153]:
df1.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [155]:
#slicing
#df[start:end]
df1[2:4]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y

In [63]:
#creation/addition
#df.append(data)
#concat


df1.append(pd.DataFrame([[800,0,0,0,0,0,0,0,0,0,0,0,0]],columns=df1.columns)) # concat
df1.tail(5)

AttributeError: 'DataFrame' object has no attribute 'append'

In [65]:

m1=pd.DataFrame([[800,0,0,0,0,0,0,0,0,0,0,0,0]])

df=pd.concat([df,m1],axis=1)

In [67]:
df=pd.concat([df,m1],axis=1)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,...,3,4,5,6,7,8,9,10,11,12
1,LP001003,Male,Yes,1,Graduate,No,4583.0,1508.0,128.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,LP001011,Male,Yes,2,Graduate,Yes,5417.0,4196.0,267.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002979,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,LP002983,Male,Yes,1,Graduate,No,8072.0,240.0,253.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,LP002984,Male,Yes,2,Graduate,No,7583.0,0.0,187.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,LP002990,Female,No,0,Graduate,Yes,4583.0,0.0,133.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [69]:
df1.tail(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [71]:
#deletion
#.drop , axis=0
df.drop(index=613,axis=0)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,...,3,4,5,6,7,8,9,10,11,12
1,LP001003,Male,Yes,1,Graduate,No,4583.0,1508.0,128.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,LP001011,Male,Yes,2,Graduate,Yes,5417.0,4196.0,267.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900.0,0.0,71.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,LP002979,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,LP002983,Male,Yes,1,Graduate,No,8072.0,240.0,253.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,LP002984,Male,Yes,2,Graduate,No,7583.0,0.0,187.0,360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [73]:
df1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

## Cleaning

In [78]:
#.rename
df1.rename(columns={'ApplicantIncome':'Applicant_Income','CoapplicantIncome':'family_Income'},inplace=True)

In [157]:
df1.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [159]:
#remove/Drop
#.drop
df1.dropna()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [88]:
df1.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,family_Income,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [161]:
#set index
#set_index
df1.set_index('Loan_ID',inplace=True)
df1.head(5)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
Loan_ID,,,,,,,,,,,,
LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [163]:
df1.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [165]:
df1.shape

(614, 12)

# explore Categorical Attributes

In [88]:
#.value_counts()  --->count of observation at each level
#.unique()  --->unique values
#.nunique()  ----> total no of unique elements

In [43]:

p_area=df1['Property_Area'].nunique()
p_area

3

In [44]:
# different variants of type 1
print(df['Property_Area'].unique())

['Rural' 'Urban' 'Semiurban' nan]

In [72]:
#count for each variant
print(df['Property_Area'].value_counts())

Semiurban    191
Urban        150
Rural        139
Name: Property_Area, dtype: int64

In [74]:
print(pd.isnull(df1['Dependents']).sum())

15

In [75]:
#condition Filtering

cred=df1[df1['Credit_History'] == 1]
cred

,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,family_Income,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
Loan_ID,,,,,,,,,,,,
LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y

In [75]:
h_l=df1[df1['Married']=='Yes']['Education'].value_counts().idxmax()
h_l

'Graduate'

In [54]:

df1['Loan_Amount_Term'].idxmax()

75

In [55]:
np.min(df['Loan_Amount_Term'])

36.0

In [56]:
np.max(df['Loan_Amount_Term'])

480.0

In [57]:
np.mean(df['Loan_Amount_Term'])

342.05

In [58]:
df1.dtypes

Gender               object
Married              object
Dependents           object
Education            object
Self_Employed        object
Applicant_Income      int64
LoanAmount          float64
Loan_Amount_Term    float64
Credit_History      float64
Property_Area        object
Loan_Status          object
family_Income       float64
dtype: object

In [59]:
df1.groupby('Gender')[['Loan_Amount_Term']].mean()

        Loan_Amount_Term
Gender
Female        352.293578
Male          339.665272

In [60]:
df1.groupby('Gender')[['Loan_Amount_Term']].mean().sort_values(by='Loan_Amount_Term',ascending=True)

        Loan_Amount_Term
Gender
Male          339.665272
Female        352.293578

In [61]:
#pivot
pd.pivot_table(df1,index='Gender',values='Loan_Amount_Term',aggfunc='sum')

        Loan_Amount_Term
Gender
Female           38400.0
Male            162360.0

In [76]:

df1=pd.DataFrame({'names':pd.Series(['rob','jen','bob'])})
df2=pd.DataFrame({'names':pd.Series(['rob','jenny','bobby'])})

In [77]:
df1

  names
0   rob
1   jen
2   bob

In [78]:
df2

   names
0    rob
1  jenny
2  bobby

In [92]:
# Merge

pd.merge(left=df1,right=df2,on='names',how='inner')

  names
0   rob

In [93]:
pd.merge(left=df1,right=df2,on='names',how='outer')

   names
0    rob
1    jen
2    bob
3  jenny
4  bobby

In [95]:
pd.merge(left=df1,right=df2,on='names',how='left')

  names
0   rob
1   jen
2   bob

In [96]:
pd.merge(left=df1,right=df2,on='names',how='right')

   names
0    rob
1  jenny
2  bobby